### ISSUE TITLE
data race in util_random.go:70

### ISSUE THREAD

**Issue by DavidHuie** [MaxHalford/gago#18]
I've got a unit test in my application that detects that a data race when running `go test -race` with the following output:
```
WARNING: DATA RACE
Read at 0x00c4202e2000 by goroutine 46:
  math/rand.(*rngSource).Int63()
      /Users/dhuie/src/go/src/math/rand/rng.go:236 +0x3f
  math/rand.(*Rand).Int63()
      /Users/dhuie/src/go/src/math/rand/rand.go:82 +0x51
  github.com/DavidHuie/REDACTED/vendor/github.com/MaxHalford/gago.randString()
      /Users/dhuie/src/github.com/DavidHuie/REDACTED/vendor/github.com/MaxHalford/gago/util_random.go:70 +0x85
  github.com/DavidHuie/REDACTED/vendor/github.com/MaxHalford/gago.(*GA).Initialize.func1()
      /Users/dhuie/src/github.com/DavidHuie/REDACTED/vendor/github.com/MaxHalford/gago/ga.go:100 +0xa8
```

**Comment by DavidHuie** [comment]
The issue here is that `rand.Rand` isn't threadsafe, but rand.Source is: https://github.com/golang/go/issues/3611

The fix is probably modify the API to pass around `rand.Source` objects.

**Comment by MaxHalford** [comment]
Hello, sorry for the late reply, I haven't been available at all and I am the only maintainer.

I will look into this and get back to you as soon as possible!

**Comment by MaxHalford** [comment]
Okay I fixed the issue. Indeed `rand.Rand` isn't thread safe but I use a separate per goroutine in all of gago. However the `GA.Initialize` method called `pop.Initialize` with a global `rand.Rand`, which lead to a data race. `go test -race` works fine now!

Thanks a lot for raising the issue.
